// Generated by mpgen from /home/zaidmstrr/bitcoin/src/ipc/capnp/common.capnp

// IWYU pragma: no_include "mp/proxy.h"
// IWYU pragma: no_include "mp/proxy-io.h"
#include <capnp/common.capnp.proxy.h>
#include <capnp/common.capnp.proxy-types.h> // IWYU pragma: keep
#include <mp/proxy-types.h>

namespace mp {
} // namespace mp
