// Generated by mpgen from /home/zaidmstrr/bitcoin/src/ipc/capnp/common.capnp

// IWYU pragma: no_include <kj/memory.h>
// IWYU pragma: no_include <memory>
// IWYU pragma: begin_keep
#include <capnp/common.capnp.h>
#include <capnp/common.capnp.proxy.h>
#include <capnp/common.capnp.proxy-types.h>
#include <capnp/capability.h>
#include <capnp/common.h>
#include <capnp/generated-header-support.h>
#include <cstring>
#include <functional>
#include <kj/common.h>
#include <map>
#include <mp/proxy.h>
#include <mp/proxy-io.h>
#include <mp/util.h>
#include <string>
#include <vector>
#include <mp/proxy-types.h>
// IWYU pragma: end_keep

namespace mp {
namespace {
} // namespace
} // namespace mp
