// Generated by mpgen from /home/zaidmstrr/bitcoin/src/ipc/capnp/echo.capnp

#ifndef CAPNP_ECHO_CAPNP_PROXY_TYPES_H
#define CAPNP_ECHO_CAPNP_PROXY_TYPES_H

#include <src/ipc/capnp/echo.capnp.proxy.h>
#include <ipc/capnp/echo-types.h>
namespace mp {
} // namespace mp
#endif
