// Generated by mpgen from /home/zaidmstrr/bitcoin/src/ipc/capnp/handler.capnp

#ifndef CAPNP_HANDLER_CAPNP_PROXY_TYPES_H
#define CAPNP_HANDLER_CAPNP_PROXY_TYPES_H

#include <handler.capnp.proxy.h>
#include <../capnp/handler-types.h> // Commented out due to missing file
namespace mp {
} // namespace mp
#endif
