// Generated by mpgen from /home/zaidmstrr/bitcoin/src/ipc/capnp/init.capnp

#include <src/ipc/capnp/init.capnp.proxy-types.h>
#include <mp/proxy-types.h>

namespace mp {
ProxyClient<ipc::capnp::messages::Init>::~ProxyClient() { clientDestroy(*this);  }
ProxyServer<ipc::capnp::messages::Init>::~ProxyServer() { serverDestroy(*this); }
} // namespace mp
