// Generated by mpgen from /home/zaidmstrr/bitcoin/src/ipc/capnp/init.capnp

#ifndef CAPNP_INIT_CAPNP_PROXY_TYPES_H
#define CAPNP_INIT_CAPNP_PROXY_TYPES_H

#include <src/ipc/capnp/init.capnp.proxy.h>
#include <ipc/capnp/init-types.h>
namespace mp {
} // namespace mp
#endif
