// Generated by mpgen from /home/zaidmstrr/bitcoin/src/ipc/capnp/mining.capnp

#ifndef CAPNP_MINING_CAPNP_PROXY_TYPES_H
#define CAPNP_MINING_CAPNP_PROXY_TYPES_H

#include <src/ipc/capnp/mining.capnp.proxy.h>
#include <ipc/capnp/mining-types.h>
namespace mp {
template<>
struct ProxyType<node::BlockCreateOptions>
{
public:
    using Struct = ipc::capnp::messages::BlockCreateOptions;
    static decltype(auto) get(std::integral_constant<size_t, 0>) { return &node::BlockCreateOptions::use_mempool; }
    static decltype(auto) get(std::integral_constant<size_t, 1>) { return &node::BlockCreateOptions::block_reserved_weight; }
    static decltype(auto) get(std::integral_constant<size_t, 2>) { return &node::BlockCreateOptions::coinbase_output_max_additional_sigops; }
    static constexpr size_t fields = 3;
};
} // namespace mp
#endif
