// Generated by mpgen from /home/zaidmstrr/bitcoin/src/ipc/capnp/rpc.capnp

#ifndef CAPNP_RPC_CAPNP_PROXY_TYPES_H
#define CAPNP_RPC_CAPNP_PROXY_TYPES_H

// IWYU pragma: no_include "mp/proxy.h"
#include <mp/proxy.h> // IWYU pragma: keep
#include <capnp/rpc.capnp.proxy.h> // IWYU pragma: keep
#include "ipc/capnp/rpc-types.h" // IWYU pragma: export
namespace mp {
} // namespace mp
#endif
