// Generated by mpgen from /home/zaidmstrr/bitcoin/src/ipc/capnp/rpc.capnp

// IWYU pragma: no_include "mp/proxy.h"
// IWYU pragma: no_include "mp/proxy-io.h"
#include <capnp/rpc.capnp.h> // IWYU pragma: keep
#include <capnp/rpc.capnp.proxy.h>
#include <capnp/rpc.capnp.proxy-types.h> // IWYU pragma: keep
#include <mp/proxy-types.h>

namespace mp {
ProxyClient<ipc::capnp::messages::Rpc>::~ProxyClient() { clientDestroy(*this);  }
ProxyServer<ipc::capnp::messages::Rpc>::~ProxyServer() { serverDestroy(*this); }
} // namespace mp
