// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: rpc.capnp

#include "rpc.capnp.h"

namespace capnp {
namespace schemas {
static const ::capnp::_::AlignedData<40> b_acb1d37f0a713129 = {
  {   0,   0,   0,   0,   6,   0,   6,   0,
     41,  49, 113,  10, 127, 211, 177, 172,
     16,   0,   0,   0,   3,   0,   0,   0,
    172,  70, 225,  69, 220,   5,  53, 156,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    194,   1,   0,   0,  86,   2,   0,   0,
     21,   0,   0,   0, 162,   0,   0,   0,
     29,   0,   0,   0,   7,   0,   0,   0,
     29,   0,   0,   0,  31,   0,   0,   0,
     65,   0,   0,   0,  71,   0,   0,   0,
    109,   0,   0,   0,   7,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     99,  97, 112, 110, 112,  47, 114, 112,
     99,  46,  99,  97, 112, 110, 112,  58,
     82, 112,  99,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   1,   0,   1,   0,
      4,   0,   0,   0,   1,   0,   2,   0,
     94,  64, 177, 183, 121,  96, 244, 230,
      4,   0,   0,   0,   2,   0,   1,   0,
     20,   0,   0,   0,   0,   0,   1,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      1,   0,   0,   0, 130,   0,   0,   0,
    105, 110, 116, 101, 114, 102,  97,  99,
    101, 115,  58,  58,  82, 112,  99,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      4,   0,   0,   0,   3,   0,   5,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     20, 169, 254,  98, 159, 191, 220, 148,
    213,  52,  61, 239, 231, 224, 154, 160,
     17,   0,   0,   0,  90,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      9,   0,   0,   0,   7,   0,   0,   0,
    101, 120, 101,  99, 117, 116, 101,  82,
    112,  99,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   1,   0,
      0,   0,   0,   0,   1,   0,   1,   0, }
};
::capnp::word const* const bp_acb1d37f0a713129 = b_acb1d37f0a713129.words;
#if !CAPNP_LITE
static const ::capnp::_::RawSchema* const d_acb1d37f0a713129[] = {
  &s_94dcbf9f62fea914,
  &s_a09ae0e7ef3d34d5,
};
static const uint16_t m_acb1d37f0a713129[] = {0};
const ::capnp::_::RawSchema s_acb1d37f0a713129 = {
  0xacb1d37f0a713129, b_acb1d37f0a713129.words, 40, d_acb1d37f0a713129, m_acb1d37f0a713129,
  2, 1, nullptr, nullptr, nullptr, { &s_acb1d37f0a713129, nullptr, nullptr, 0, 0, nullptr }, false
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<79> b_94dcbf9f62fea914 = {
  {   0,   0,   0,   0,   6,   0,   6,   0,
     20, 169, 254,  98, 159, 191, 220, 148,
     20,   0,   0,   0,   1,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      4,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0,  50,   1,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     29,   0,   0,   0, 231,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     99,  97, 112, 110, 112,  47, 114, 112,
     99,  46,  99,  97, 112, 110, 112,  58,
     82, 112,  99,  46, 101, 120, 101,  99,
    117, 116, 101,  82, 112,  99,  36,  80,
     97, 114,  97, 109, 115,   0,   0,   0,
     16,   0,   0,   0,   3,   0,   4,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     97,   0,   0,   0,  66,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     92,   0,   0,   0,   3,   0,   1,   0,
    104,   0,   0,   0,   2,   0,   1,   0,
      1,   0,   0,   0,   1,   0,   0,   0,
      0,   0,   1,   0,   1,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    101,   0,   0,   0,  66,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     96,   0,   0,   0,   3,   0,   1,   0,
    108,   0,   0,   0,   2,   0,   1,   0,
      2,   0,   0,   0,   2,   0,   0,   0,
      0,   0,   1,   0,   2,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    105,   0,   0,   0,  34,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    100,   0,   0,   0,   3,   0,   1,   0,
    112,   0,   0,   0,   2,   0,   1,   0,
      3,   0,   0,   0,   3,   0,   0,   0,
      0,   0,   1,   0,   3,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    109,   0,   0,   0,  42,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    104,   0,   0,   0,   3,   0,   1,   0,
    116,   0,   0,   0,   2,   0,   1,   0,
     99, 111, 110, 116, 101, 120, 116,   0,
     16,   0,   0,   0,   0,   0,   0,   0,
    198,  34,  11,  93, 100, 230,  68, 156,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     16,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    114, 101, 113, 117, 101, 115, 116,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    117, 114, 105,   0,   0,   0,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    117, 115, 101, 114,   0,   0,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_94dcbf9f62fea914 = b_94dcbf9f62fea914.words;
#if !CAPNP_LITE
static const ::capnp::_::RawSchema* const d_94dcbf9f62fea914[] = {
  &s_9c44e6645d0b22c6,
};
static const uint16_t m_94dcbf9f62fea914[] = {0, 1, 2, 3};
static const uint16_t i_94dcbf9f62fea914[] = {0, 1, 2, 3};
const ::capnp::_::RawSchema s_94dcbf9f62fea914 = {
  0x94dcbf9f62fea914, b_94dcbf9f62fea914.words, 79, d_94dcbf9f62fea914, m_94dcbf9f62fea914,
  1, 4, i_94dcbf9f62fea914, nullptr, nullptr, { &s_94dcbf9f62fea914, nullptr, nullptr, 0, 0, nullptr }, true
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<34> b_a09ae0e7ef3d34d5 = {
  {   0,   0,   0,   0,   6,   0,   6,   0,
    213,  52,  61, 239, 231, 224, 154, 160,
     20,   0,   0,   0,   1,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      1,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0,  58,   1,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     29,   0,   0,   0,  63,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     99,  97, 112, 110, 112,  47, 114, 112,
     99,  46,  99,  97, 112, 110, 112,  58,
     82, 112,  99,  46, 101, 120, 101,  99,
    117, 116, 101,  82, 112,  99,  36,  82,
    101, 115, 117, 108, 116, 115,   0,   0,
      4,   0,   0,   0,   3,   0,   4,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     13,   0,   0,   0,  58,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      8,   0,   0,   0,   3,   0,   1,   0,
     20,   0,   0,   0,   2,   0,   1,   0,
    114, 101, 115, 117, 108, 116,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_a09ae0e7ef3d34d5 = b_a09ae0e7ef3d34d5.words;
#if !CAPNP_LITE
static const uint16_t m_a09ae0e7ef3d34d5[] = {0};
static const uint16_t i_a09ae0e7ef3d34d5[] = {0};
const ::capnp::_::RawSchema s_a09ae0e7ef3d34d5 = {
  0xa09ae0e7ef3d34d5, b_a09ae0e7ef3d34d5.words, 34, nullptr, m_a09ae0e7ef3d34d5,
  0, 1, i_a09ae0e7ef3d34d5, nullptr, nullptr, { &s_a09ae0e7ef3d34d5, nullptr, nullptr, 0, 0, nullptr }, false
};
#endif  // !CAPNP_LITE
}  // namespace schemas
}  // namespace capnp

// =======================================================================================

namespace ipc {
namespace capnp {
namespace messages {

#if !CAPNP_LITE
::capnp::Request< ::ipc::capnp::messages::Rpc::ExecuteRpcParams,  ::ipc::capnp::messages::Rpc::ExecuteRpcResults>
Rpc::Client::executeRpcRequest(::kj::Maybe< ::capnp::MessageSize> sizeHint) {
  return newCall< ::ipc::capnp::messages::Rpc::ExecuteRpcParams,  ::ipc::capnp::messages::Rpc::ExecuteRpcResults>(
      0xacb1d37f0a713129ull, 0, sizeHint, {true});
}
::kj::Promise<void> Rpc::Server::executeRpc(ExecuteRpcContext) {
  return ::capnp::Capability::Server::internalUnimplemented(
      "capnp/rpc.capnp:Rpc", "executeRpc",
      0xacb1d37f0a713129ull, 0);
}
::capnp::Capability::Server::DispatchCallResult Rpc::Server::dispatchCall(
    uint64_t interfaceId, uint16_t methodId,
    ::capnp::CallContext< ::capnp::AnyPointer, ::capnp::AnyPointer> context) {
  switch (interfaceId) {
    case 0xacb1d37f0a713129ull:
      return dispatchCallInternal(methodId, context);
    default:
      return internalUnimplemented("capnp/rpc.capnp:Rpc", interfaceId);
  }
}
::capnp::Capability::Server::DispatchCallResult Rpc::Server::dispatchCallInternal(
    uint16_t methodId,
    ::capnp::CallContext< ::capnp::AnyPointer, ::capnp::AnyPointer> context) {
  switch (methodId) {
    case 0:
      return {
        executeRpc(::capnp::Capability::Server::internalGetTypedContext<
             ::ipc::capnp::messages::Rpc::ExecuteRpcParams,  ::ipc::capnp::messages::Rpc::ExecuteRpcResults>(context)),
        false,
        false
      };
    default:
      (void)context;
      return ::capnp::Capability::Server::internalUnimplemented(
          "capnp/rpc.capnp:Rpc",
          0xacb1d37f0a713129ull, methodId);
  }
}
#endif  // !CAPNP_LITE

// Rpc
#if !CAPNP_LITE
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr ::capnp::Kind Rpc::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* Rpc::_capnpPrivate::schema;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#endif  // !CAPNP_LITE

// Rpc::ExecuteRpcParams
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr uint16_t Rpc::ExecuteRpcParams::_capnpPrivate::dataWordSize;
constexpr uint16_t Rpc::ExecuteRpcParams::_capnpPrivate::pointerCount;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#if !CAPNP_LITE
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr ::capnp::Kind Rpc::ExecuteRpcParams::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* Rpc::ExecuteRpcParams::_capnpPrivate::schema;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#endif  // !CAPNP_LITE

// Rpc::ExecuteRpcResults
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr uint16_t Rpc::ExecuteRpcResults::_capnpPrivate::dataWordSize;
constexpr uint16_t Rpc::ExecuteRpcResults::_capnpPrivate::pointerCount;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#if !CAPNP_LITE
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr ::capnp::Kind Rpc::ExecuteRpcResults::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* Rpc::ExecuteRpcResults::_capnpPrivate::schema;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#endif  // !CAPNP_LITE


}  // namespace
}  // namespace
}  // namespace

