// Generated by mpgen from /home/zaidmstrr/bitcoin/src/ipc/capnp/rpc.capnp

#ifndef CAPNP_RPC_CAPNP_PROXY_H
#define CAPNP_RPC_CAPNP_PROXY_H

#include <capnp/rpc.capnp.h> // IWYU pragma: keep
#include "interfaces/rpc.h" // IWYU pragma: export
#include <mp/proxy.h>

#if defined(__GNUC__)
#pragma GCC diagnostic push
#if !defined(__has_warning)
#pragma GCC diagnostic ignored "-Wsuggest-override"
#elif __has_warning("-Wsuggest-override")
#pragma GCC diagnostic ignored "-Wsuggest-override"
#endif
#endif
namespace mp {
template<>
struct ProxyMethod<ipc::capnp::messages::Rpc::ExecuteRpcParams>
{
    static constexpr auto impl = &interfaces::Rpc::executeRpc;
};

namespace rpc_fields {
struct Context
{
    template<typename S> static auto get(S&& s) -> decltype(s.getContext()) { return s.getContext(); }
    template<typename S> static bool has(S&& s) { return s.hasContext(); }
    template<typename S, typename A> static void set(S&& s, A&& a) { s.setContext(std::forward<A>(a)); }
    template<typename S, typename... A> static decltype(auto) init(S&& s, A&&... a) { return s.initContext(std::forward<A>(a)...); }
    template<typename S> static bool getWant(S&& s) { return s.getWantContext(); }
    template<typename S> static void setWant(S&& s) { s.setWantContext(true); }
    template<typename S> static bool getHas(S&& s) { return s.getHasContext(); }
    template<typename S> static void setHas(S&& s) { s.setHasContext(true); }
};
struct Request
{
    template<typename S> static auto get(S&& s) -> decltype(s.getRequest()) { return s.getRequest(); }
    template<typename S> static bool has(S&& s) { return s.hasRequest(); }
    template<typename S, typename A> static void set(S&& s, A&& a) { s.setRequest(std::forward<A>(a)); }
    template<typename S, typename... A> static decltype(auto) init(S&& s, A&&... a) { return s.initRequest(std::forward<A>(a)...); }
    template<typename S> static bool getWant(S&& s) { return s.getWantRequest(); }
    template<typename S> static void setWant(S&& s) { s.setWantRequest(true); }
    template<typename S> static bool getHas(S&& s) { return s.getHasRequest(); }
    template<typename S> static void setHas(S&& s) { s.setHasRequest(true); }
};
struct Uri
{
    template<typename S> static auto get(S&& s) -> decltype(s.getUri()) { return s.getUri(); }
    template<typename S> static bool has(S&& s) { return s.hasUri(); }
    template<typename S, typename A> static void set(S&& s, A&& a) { s.setUri(std::forward<A>(a)); }
    template<typename S, typename... A> static decltype(auto) init(S&& s, A&&... a) { return s.initUri(std::forward<A>(a)...); }
    template<typename S> static bool getWant(S&& s) { return s.getWantUri(); }
    template<typename S> static void setWant(S&& s) { s.setWantUri(true); }
    template<typename S> static bool getHas(S&& s) { return s.getHasUri(); }
    template<typename S> static void setHas(S&& s) { s.setHasUri(true); }
};
struct User
{
    template<typename S> static auto get(S&& s) -> decltype(s.getUser()) { return s.getUser(); }
    template<typename S> static bool has(S&& s) { return s.hasUser(); }
    template<typename S, typename A> static void set(S&& s, A&& a) { s.setUser(std::forward<A>(a)); }
    template<typename S, typename... A> static decltype(auto) init(S&& s, A&&... a) { return s.initUser(std::forward<A>(a)...); }
    template<typename S> static bool getWant(S&& s) { return s.getWantUser(); }
    template<typename S> static void setWant(S&& s) { s.setWantUser(true); }
    template<typename S> static bool getHas(S&& s) { return s.getHasUser(); }
    template<typename S> static void setHas(S&& s) { s.setHasUser(true); }
};
struct Result
{
    template<typename S> static auto get(S&& s) -> decltype(s.getResult()) { return s.getResult(); }
    template<typename S> static bool has(S&& s) { return s.hasResult(); }
    template<typename S, typename A> static void set(S&& s, A&& a) { s.setResult(std::forward<A>(a)); }
    template<typename S, typename... A> static decltype(auto) init(S&& s, A&&... a) { return s.initResult(std::forward<A>(a)...); }
    template<typename S> static bool getWant(S&& s) { return s.getWantResult(); }
    template<typename S> static void setWant(S&& s) { s.setWantResult(true); }
    template<typename S> static bool getHas(S&& s) { return s.getHasResult(); }
    template<typename S> static void setHas(S&& s) { s.setHasResult(true); }
};
} // namespace rpc_fields

template<>
struct ProxyClient<ipc::capnp::messages::Rpc> final : public ProxyClientCustom<ipc::capnp::messages::Rpc, interfaces::Rpc>
{
public:
    using ProxyClientCustom::ProxyClientCustom;
    ~ProxyClient();
    using M0 = ProxyClientMethodTraits<ipc::capnp::messages::Rpc::ExecuteRpcParams>;
    typename M0::Result executeRpc(M0::Param<0> request,M0::Param<1> uri,M0::Param<2> user);
};

template<>
struct ProxyServer<ipc::capnp::messages::Rpc> : public ProxyServerCustom<ipc::capnp::messages::Rpc, interfaces::Rpc>
{
public:
    using ProxyServerCustom::ProxyServerCustom;
    ~ProxyServer();
    kj::Promise<void> executeRpc(ExecuteRpcContext call_context) override;
};

template<>
struct ProxyType<interfaces::Rpc>
{
    using Type = interfaces::Rpc;
    using Message = ipc::capnp::messages::Rpc;
    using Client = ProxyClient<Message>;
    using Server = ProxyServer<Message>;
};
} // namespace mp
#if defined(__GNUC__)
#pragma GCC diagnostic pop
#endif
#endif
