// Generated by mpgen from /home/zaidmstrr/bitcoin/src/ipc/capnp/rpc.capnp

// IWYU pragma: no_include <kj/memory.h>
// IWYU pragma: no_include <memory>
// IWYU pragma: begin_keep
#include <capnp/rpc.capnp.h>
#include <capnp/rpc.capnp.proxy.h>
#include <capnp/rpc.capnp.proxy-types.h>
#include <capnp/capability.h>
#include <capnp/common.h>
#include <capnp/generated-header-support.h>
#include <cstring>
#include <functional>
#include <kj/common.h>
#include <map>
#include <mp/proxy.h>
#include <mp/proxy-io.h>
#include <mp/util.h>
#include <string>
#include <vector>
#include <mp/proxy-types.h>
// IWYU pragma: end_keep

namespace mp {
ProxyClient<ipc::capnp::messages::Rpc>::M0::Result ProxyClient<ipc::capnp::messages::Rpc>::executeRpc(M0::Param<0> request,M0::Param<1> uri,M0::Param<2> user) {
    typename M0::Result result;
    clientInvoke(*this, &ipc::capnp::messages::Rpc::Client::executeRpcRequest, MakeClientParam<Accessor<rpc_fields::Context, FIELD_IN | FIELD_BOXED>>(), MakeClientParam<Accessor<rpc_fields::Request, FIELD_IN | FIELD_BOXED>>(M0::Fwd<0>(request)), MakeClientParam<Accessor<rpc_fields::Uri, FIELD_IN | FIELD_BOXED>>(M0::Fwd<1>(uri)), MakeClientParam<Accessor<rpc_fields::User, FIELD_IN | FIELD_BOXED>>(M0::Fwd<2>(user)), MakeClientParam<Accessor<rpc_fields::Result, FIELD_OUT | FIELD_BOXED>>(result));
    return result;
}
namespace {
ProxyTypeRegister t12443959787990888745{TypeList<interfaces::Rpc>{}};
} // namespace
} // namespace mp
